const menu:any=[
 {
   title:"USER",
   id:'user',
   child:[
     {
       title:'用户管理',
       id:'userManage',
       icon:'setting',
       isUnfold:false,
       child:[
         {
            title:'option1',
            id:'option1',
            url:'/admin/user'
         },
         {
          title:'option2',
          id:'option2',
          url:'/admin/user'
         }
    
       ]
     }
   ]
  },
 {
   title:"SHOPING",
   id:'user',
   child:[
    {
      title:'商品管理',
      id:'productManage',
      icon:'setting',
      isUnfold:false,
      child:[
        {
           title:'商品列表',
           id:'option1',
           url:'/admin/store-management'
        }
      ]
    },
    {
      title:'商品抢购',
      id:'userManage',
      icon:'shopping-cart',
      isUnfold:false,
      url:'/admin/shopping'
    }
   ]
  }
];
export default menu;